stages:
  - lint
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  LC_ALL: en_US.UTF-8
  course: cse160
  quarter: 26sp
  source_path: _build/html

flake8:
  stage: lint
  tags:
    - courseweb
  script:
    - pip install flake8
    - python3 -m flake8

mystmd:
  stage: build
  tags:
    - courseweb
  variables:
    BASE_URL: /courses/$course/$quarter
    TYPST_GITHUB: https://github.com/typst/typst
    TYPST_VERSION: 0.14.2
    TYPST_TARGET: typst-x86_64-unknown-linux-musl
  before_script:
    - export PATH="/home/gitlab-runner/.local/bin/:$PATH"
    - |
      if ! typst --version 2>/dev/null | grep -q "$TYPST_VERSION"; then
        curl -L $TYPST_GITHUB/releases/download/v$TYPST_VERSION/$TYPST_TARGET.tar.xz \
        | xz -d \
        | tar xvf - -C /home/gitlab-runner/.local/bin/ --strip-components 1 $TYPST_TARGET/typst
      fi
    - typst --version
    - export TYPST_FONT_PATHS="$PWD/fonts"
  script:
    - pip install nodeenv matplotlib
    - nodeenv -n 24.14.1 node_env
    - source node_env/bin/activate
    - npm install
    - npx mystmd build --typst
    - npx mystmd build --execute --html
  artifacts:
    paths:
      - $source_path
      - _build/exports

courseweb:
  stage: deploy
  tags:
    - courseweb
  script:
    - /www/utils/deploycourseweb.sh
  cache: {}
  variables:
    delete: 'yes' # https://yaml.org/type/bool.html
    GIT_STRATEGY: none
  only:
    - main
  dependencies:
    - mystmd
