stages:
  - lint
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  LC_ALL: en_US.UTF-8
  course: cse160
  quarter: 26sp
  source_path: _build/html

flake8:
  stage: lint
  tags:
    - courseweb
  script:
    - pip install flake8
    - python3 -m flake8

mystmd:
  stage: build
  tags:
    - courseweb
  variables:
    BASE_URL: /courses/$course/$quarter
  script:
    - export PATH="/home/gitlab-runner/.local/bin/:$PATH"
    - pip install nodeenv
    - nodeenv -n 24.14.1 node_env
    - source node_env/bin/activate
    - >
      curl -L https://github.com/typst/typst/releases/download/v0.14.2/typst-x86_64-unknown-linux-musl.tar.xz
      | xz -d
      | tar xvf - -C ~/.local/bin/ --strip-components 1 typst-x86_64-unknown-linux-musl/typst
    - npm install
    - npx mystmd build --typst
    - npx mystmd build --html
  artifacts:
    paths:
      - $source_path
      - _build/exports

courseweb:
  stage: deploy
  tags:
    - courseweb
  script:
    - /www/utils/deploycourseweb.sh
  cache: {}
  variables:
    delete: 'yes' # https://yaml.org/type/bool.html
    GIT_STRATEGY: none
  only:
    - main
  dependencies:
    - mystmd
