# Utility Functions - DO NOT MODIFY THIS FILE!

import itertools
from PIL import Image
import sys


def csv_line_to_pixels(line):
    """
    Given a CSV-formatted row of integers, returns the integers as a list. The argument line must
    be a string such as

        "255, 0,  27"

    There must be no extra spaces at the beginning or end of the string, and commas can only exist
    between elements (no comma before the first element, and no comma after the last one). Raises
    an error if either of these assumptions are not valid.
    """
    row = []
    for pixel in line.split(","):
        row.append(int(pixel))
    return row


def convert_to_grayscale(input_file, out_file):
    try:
        in_image = Image.open(input_file)
    except IOError as e:
        print(e)
        sys.exit(1)
    except Exception:
        print("Unexpected error reading file", input_file)
        sys.exit(1)

    out_image = in_image.convert("L")

    try:
        out_image.save(out_file, "PNG")
    except IOError as e:
        print(e)
    except Exception:
        print("Unexpected error writing file", out_file)


def read_image(file_path):
    """
    Reads the image file at file_path and returns it as a rectangular pixel grid. Each element of
    the outer list is one row of pixels, where each pixel is an integer x such that 0 <= x < 256.
    """
    print("Reading image", file_path)

    try:
        image_file = Image.open(file_path)
    except IOError as e:
        print(e)
        return
    except Exception:
        print("Unexpected error reading file", file_path)
        return

    width, height = image_file.size
    data = list(image_file.getdata())

    # data is a single list. We break it into a nested list.
    result = []
    for r in range(height):
        # Get the part of the list that corresponds to this row.
        row_start = r * width
        row = data[row_start:row_start + width]

        result.append(row)
    return result


def write_image(file_name, pixel_grid):
    """
    Given a pixel_grid, write it to the file_name as an image. Each row of pixel_grid must have the
    same length, and each pixel value must be an integer x such that 0 <= x < 256.
    """
    size = len(pixel_grid[0]), len(pixel_grid)
    image = Image.new("L", size)

    print("Writing", size[0], "x", size[1], "image to file", file_name)

    # Flatten the list.
    data = list(itertools.chain.from_iterable(pixel_grid))
    image.putdata(data)

    try:
        # Write the image using the encoding specified in the file_name.
        image.save(file_name)
    except IOError as e:
        print(e)
    except Exception:
        print("Unexpected error writing file", file_name)


def write_grid(file_name, pixel_grid):
    """Writes the given pixel_grid to filename file_name as CSV."""
    output_file = open(file_name, "w")

    for row in pixel_grid:
        output_file.write(str(row[0]))
        for column in range(1, len(row)):
            output_file.write(", " + str(row[column]).rjust(3))
        output_file.write("\n")

    output_file.close()


def parse_args():
    if len(sys.argv) == 1:
        return None
    elif len(sys.argv) == 2:
        return sys.argv[1]
    else:
        # Print how to use the program correctly if it appears that it has been used incorrectly.
        print("Usage:", sys.argv[0], "<input_file>")
        print("  <input_file> should be either ")
        print("    (a) a CSV file")
        print("        generated by the write_grid function, or")
        print("    (b) a black-and-white image file")
        print("        generated by the convert_to_grayscale function.")
        print()
        print("  Blurs the given input file and outputs the result as:")
        print("   <input_file>_blurry.png (an image) and")
        print("   <input_file>_blurry_grid.csv (a CSV file).")
        sys.exit()
